#!/usr/bin/env bash

TRUE_REG='^([tT][rR][uU][eE]|[yY]|[yY][eE][sS]|1)$'
FALSE_REG='^([fF][aA][lL][sS][eE]|[nN]|[nN][oO]|0)$'

IS_DEBUG=${IS_DEBUG:-false}
if [[ $IS_DEBUG =~ $TRUE_REG ]]; then
    set -o xtrace
fi

IS_STRICT=${IS_STRICT:-false}
if [[ $IS_STRICT =~ $TRUE_REG ]]; then
    set -o errexit
    set -o nounset
    set -o pipefail
fi

case "$1" in
    remove)

    MATTERMOST_USER=${MATTERMOST_USER:-mattermost}
    MATTERMOST_GROUP=${MATTERMOST_GROUP:-mattermost}
    if id $MATTERMOST_USER > /dev/null 2>&1 ; then
        deluser "$MATTERMOST_USER" > /dev/null 2>&1
    fi
    if getent group "$MATTERMOST_GROUP" > /dev/null 2>&1 ; then
       delgroup "$MATTERMOST_GROUP" > /dev/null 2>&1
    fi

    systemctl daemon-reload
    ;;
esac
