#!/usr/bin/env bash

set -e
IS_UPGRADE=false

case "$1" in
    upgrade)

    systemctl stop mattermost

    # If $1=configure and $2 is set, this is an upgrade
    if [ "$2" != "" ]; then
        IS_UPGRADE=true
    fi

    if [ "$IS_UPGRADE" == "true" ]; then
        # Cleaning up old files
        find /opt/mattermost/ /opt/mattermost/client/ -mindepth 1 -maxdepth 1 \! \( -type d \( -path /opt/mattermost/client -o -path /opt/mattermost/client/plugins -o -path /opt/mattermost/config -o -path /opt/mattermost/logs -o -path /opt/mattermost/plugins -o -path /opt/mattermost/data \) -prune \) -exec rm -r {} \;
    fi
    ;;
esac
